type Query {
    me: User
    accountById(id: ID!): Account
    recentTransactions(limit: Int): [Transaction]
}

type User {
    id: ID!
    username: String!
    email: String!
    accounts: [Account]
}

type Account {
    id: ID!
    name: String!
    balance: Float!
    history(limit: Int): [Transaction]
}

type Transaction {
    id: ID!
    amount: Float!
    description: String!
    category: String!
}

type TransactionPayload {
    transaction: Transaction
    account: Account
    success: Boolean!
}

type Mutation {
    createTransaction(accountId: ID!, amount: Float!, description: String!): TransactionPayload
}