type Query {
    me: User
    accountById(id: ID!): Account
}

type Mutation {
    createTransaction(input: TransactionInput!): TransactionPayload
}

type User {
    id: ID!
    username: String!
    email: String!
    accounts: [Account]
    totalNetWorth: Float!
    monthlySubscriptionCommitted: Float!
    monthlySpending(category: Category): [CategoryTotal!]
}

type CategoryTotal {
    category: Category!
    amount: Float!
}

type Account {
    id: ID!
    name: String!
    balance: Float!
    history(limit: Int): [Transaction]
}

type Transaction {
    id: ID!
    amount: Float!
    description: String!
    category: Category!
    isSubscription: Boolean!
}

input TransactionInput {
    accountId: ID!
    amount: Float!
    description: String!
    category: Category!
}

type TransactionPayload {
    success: Boolean!
    transaction: Transaction
    account: Account
}

enum Category {
    HOUSING
    FOOD
    TRANSPORT
    ENTERTAINMENT
    UTILITIES
    INCOME
    SUBSCRIPTION
    MISCELLANEOUS
}